### ISSUE TITLE
Persistent changes to index.html?

### ISSUE THREAD

**Issue by serzhiio** [DioxusLabs/cli#106]
Lets say i want to add some classes and styles to `html`, `body` and `div[id=main]` tags, but if i change `./assets/index.html` it will be rewritten after next run of `dioxus serve` command. So how to make persistent changes?

**Comment by Demonthos** [comment]
If you create a html file in the root of your project the dioxus cli will use it. We need to document this feature and probably insert the init script by default in the future

```html
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    <div id="main">
    </div>
    <!-- this is currently needed, but should probably be inserted by default in the future -->
    <script type="module">
        import init from "/{base_path}/assets/dioxus/{app_name}.js";
        init("/{base_path}/assets/dioxus/{app_name}_bg.wasm").then(wasm => {
            if (wasm.__wbindgen_start == undefined) {
                wasm.main();
            }
        });
    </script>
</body>

</html>
```
