### ISSUE TITLE
Failed to parse

### ISSUE THREAD

**Issue by wackazong** [DioxusLabs/cli#116]
I am trying to move to dioxus-cli from trunk. My trunk setup works fine. When I run `dioxus serve` I get the error message: 

    [INFO] 🚅 Running build command...
    [INFO] 👑 Build done.
    [WARN] failed to parse `name` custom section Invalid name type (at offset 135284975)

This is rather generic, can you give me any pointers on what the problem could be? Thanks.

**Comment by mrxiaozhuox** [comment]
You don't need to pay attention to this Warning

**Comment by wackazong** [comment]
Ok, then it is another problem since I just get a blank page instead of the app.
