### ISSUE TITLE
How to make static settings available for all components

### ISSUE THREAD

**Issue by wackazong** [DioxusLabs/cli#117]
I have some settings that I load from a URL at app start. They never change during the app lifetime. Is there a better way to make them available globally than use_shared_state? Or is that the way to go?

**Comment by Demonthos** [comment]
You can use [Lazy](https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html), or [provide_context](https://docs.rs/dioxus/latest/dioxus/prelude/struct.ScopeState.html#method.provide_context) and [consume_context](https://docs.rs/dioxus/latest/dioxus/prelude/struct.ScopeState.html#method.consume_context)

In the future the discussions on the main Dioxus repo or the help channel in our discord (https://discord.com/invite/XgGxMSkvUM) are a good place to ask there kinds of questions

**Comment by wackazong** [comment]
Ok, thank you!
