### ISSUE TITLE
Error while installing dioxus-cli : 

### ISSUE THREAD

**Issue by rhacker** [DioxusLabs/cli#119]
It keeps having error at this staging of compiling dioxus: 

```
   Compiling ucd-trie v0.1.5
error: unknown start of token: \u{0}
 --> <delete-path>\scoop\persist\rustup-msvc\.cargo\registry\src\github.com-1ecc6299db9ec823\ucd-trie-0.1.5\src\lib.rs:1:1
  |
1.|.
  | ^
  |
  = help: source files must contain UTF-8 encoded text, unexpected null bytes might occur when a different encoding is used
  = note: character appears 3828 more times
```

It's on Windows, do we have binary released so it's easier to install? Thanks

**Comment by mrxiaozhuox** [comment]
can you use `rustup update stable` to update your rust version?

**Comment by mrxiaozhuox** [comment]
> can you use `rustup update stable` to update your rust version?

maybe that can solve your problem.

**Comment by rhacker** [comment]
it works now by reinstalling, thanks for answer ;)
