### ISSUE TITLE
Default target directory to target/dist/

### ISSUE THREAD

**Issue by pickfire** [DioxusLabs/cli#128]
Since rust already puts everything that was generated in build time in `target/`, maybe it would be good for dioxus to put `dist/` folder there since it is for stuff that is generated too?

**Comment by mrxiaozhuox** [comment]
`/target` is just for wasm build, but `/dist` will include the whole deploy structure, like HTML, assets, wasm, and js.

**Comment by pickfire** [comment]
Yes, I know it's for wasm build, but what I am suggesting here is use `/target` for everything, I believe `target/dist/` is unused.

**Comment by mrxiaozhuox** [comment]
You can change it in Dioxus.toml config.

**Comment by pickfire** [comment]
Yes, I already changed it, but I am suggested it to be a default.

**Comment by mrxiaozhuox** [comment]
I still think we need to divide two directories, `/target/*` just for rust build work, but `/dist/*` from Dioxus-CLI, but if u have this demand, just change the config.

**Comment by mrxiaozhuox** [comment]
but thanks for your advice 😄

**Comment by pickfire** [comment]
I guess then we can close this.
