### ISSUE TITLE
CLI should support CORS in dev server

### ISSUE THREAD

**Issue by chaosprint** [DioxusLabs/cli#135]
https://github.com/tokio-rs/axum/blob/c7d4af9bd8031f85244319dbd12f1d0698b12432/examples/cors/src/main.rs

Without CORS, we cannot use SharedArrayBuffer for WASM

**Comment by mrxiaozhuox** [comment]
![image](https://user-images.githubusercontent.com/41265098/236549225-0d666ff2-9d77-426f-be5f-e324fc9f7659.png)

**Comment by mrxiaozhuox** [comment]
I think it is caused by your PR.

**Comment by chaosprint** [comment]
> I think it is caused by your PR.

interesting, so perhaps should make it as am cli option?

**Comment by mrxiaozhuox** [comment]
yes, can you do it? because currently my fork version are working for plugin system. ❤️
