### ISSUE TITLE
Error on MacOS

### ISSUE THREAD

**Issue by maccesch** [DioxusLabs/cli#14]
I just installed dioxus-cli on my macbook pro (os version 12.2.1 (21D62)).

I tried running
```
dioxus create someproject
```
but got this error:

```
error: Found argument 'gh:dioxuslabs/dioxus-template' which wasn't expected, or isn't valid in this context

USAGE:
    cargo generate [FLAGS] [OPTIONS] --git <git>

For more information try --help
[ERROR] create error: Generate project failed.
```

Same thing happens when I provide the `--template` option.

**Comment by yaoye6262** [comment]
`dioxus create project_name`

but got this error:
`Found argument 'create' which wasn't expected, or isn't valid in this context

USAGE:
    dioxus [FLAGS] <SUBCOMMAND>

For more information try --help`

**Comment by mrxiaozhuox** [comment]
> `dioxus create project_name`
> 
> but got this error: `Found argument 'create' which wasn't expected, or isn't valid in this context
> 
> USAGE: dioxus [FLAGS]
> 
> For more information try --help`

can you show me the `dioxus --help` context ?

**Comment by mrxiaozhuox** [comment]
> I just installed dioxus-cli on my macbook pro (os version 12.2.1 (21D62)).
> 
> I tried running
> 
> ```
> dioxus create someproject
> ```
> 
> but got this error:
> 
> ```
> error: Found argument 'gh:dioxuslabs/dioxus-template' which wasn't expected, or isn't valid in this context
> 
> USAGE:
>     cargo generate [FLAGS] [OPTIONS] --git <git>
> 
> For more information try --help
> [ERROR] create error: Generate project failed.
> ```
> 
> Same thing happens when I provide the `--template` option.

You are using the github-master branch version cli ?

**Comment by mrxiaozhuox** [comment]
> I just installed dioxus-cli on my macbook pro (os version 12.2.1 (21D62)).
> 
> I tried running
> 
> ```
> dioxus create someproject
> ```
> 
> but got this error:
> 
> ```
> error: Found argument 'gh:dioxuslabs/dioxus-template' which wasn't expected, or isn't valid in this context
> 
> USAGE:
>     cargo generate [FLAGS] [OPTIONS] --git <git>
> 
> For more information try --help
> [ERROR] create error: Generate project failed.
> ```
> 
> Same thing happens when I provide the `--template` option.

Can you check if `cargo generate` Is installed on your os ?

**Comment by maccesch** [comment]
@mrxiaozhuox I just confirmed. It is installed. This is the output of `dioxus --help`:

```
dioxus 
Build, bundle, & ship your Dioxus app

USAGE:
    dioxus [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information
    -v            Enable verbose logging

SUBCOMMANDS:
    build        Build the Rust WASM app and all of its assets
    clean        Clean output artifacts
    config       Dioxus config file controls
    create       Init a new project for Dioxus
    help         Print this message or the help of the given subcommand(s)
    serve        Build, watch & serve the Rust WASM app and all of its assets
    translate    Translate some source file into Dioxus code
```

**Comment by maccesch** [comment]
@yaoye6262 You probably installed the latest release version where the `generate` command isn't included yet. That's why I installed the latest directly from github but got the error mentioned above.

**Comment by yaoye6262** [comment]
dioxus --help context:

`
dioxus 0.1.1
Build, bundle, & ship your Dioxus app

USAGE:
    dioxus [FLAGS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -v               Enable verbose logging
    -V, --version    Prints version information

SUBCOMMANDS:
    help         Prints this message or the help of the given subcommand(s)
    translate    Translate some source file into Dioxus code
`

**Comment by yaoye6262** [comment]
@maccesch @mrxiaozhuox 

OK！Has been resolved！

**Comment by maccesch** [comment]
I'm still getting the same error

**Comment by mrxiaozhuox** [comment]
> @yaoye6262 You probably installed the latest release version where the `generate` command isn't included yet. That's why I installed the latest directly from github but got the error mentioned above.

can you try to change `generate` version to the latest version ?

**Comment by maccesch** [comment]
I updated rust and cargo-generate to the latest versions and now it works.

Should there be a check that you have the correct version of cargo-generate installed?

**Comment by mrxiaozhuox** [comment]
> I updated rust and cargo-generate to the latest versions and now it works.
> 
> Should there be a check that you have the correct version of cargo-generate installed?

yes, `dioxus-cli` will install the latest generate, probably because you've installed it before

**Comment by maccesch** [comment]
yes, makes sense. What I wanted to say is this:

When `dioxus generate` is called, it should check if the installed version of cargo-generate is up to date.

**Comment by mrxiaozhuox** [comment]
> yes, makes sense. What I wanted to say is this:
> 
> When `dioxus generate` is called, it should check if the installed version of cargo-generate is up to date.

yes ! good idea !! 😄
