### ISSUE TITLE
Serve not working

### ISSUE THREAD

**Issue by gianzellweger** [DioxusLabs/cli#141]
**What caused the issue?**

I tried to use `dioxus serve` in a project.

**What happened?**

Nothing showed on the page, so I opened DevTools which look like this:
![image](https://github.com/DioxusLabs/cli/assets/97334144/d25b1c52-0541-4186-b6ef-d8a94bb8fc89)

The full text can be found at https://pastebin.com/jCsfyJFX

**What was expected?**

I expected the application I made to show up.

**Attempts at fixing it**

I tried different versions of the CLI (not older ones though as I didn't get them to work quickly) and none of them work. I have also tried both Linux and macOS. I also tried macOS on both arm64 and x86. Nothing worked.

**Comment by mrxiaozhuox** [comment]
which one cli version you using? git master?

**Comment by gianzellweger** [comment]
Both the most recent rev which I installed with `cargo install --git https://github.com/dioxuslabs/cli --rev 2bbf69e` and also just the most recent stable release which I installed with `cargo install dioxus-cli`.

**Comment by Demonthos** [comment]
This is an issue with Dioxus web. See https://github.com/DioxusLabs/dioxus/issues/944

**Comment by gianzellweger** [comment]
The issue was resolved by me switching the toolchain from nightly to stable.
