### ISSUE TITLE
Init script isn't added to custom index file

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/cli#146]
**Problem**

When using a custom ``index.html`` file, the init script isn't added to the body tag, and wasm isn't run, causing nothing to render.
The script tag in question:
```js
<script type="module">
  import init from "/{base_path}/assets/dioxus/{app_name}.js";
  init("/{base_path}/assets/dioxus/{app_name}_bg.wasm").then(wasm => {
    if (wasm.__wbindgen_start == undefined) {
      wasm.main();
    }
  });
</script>
```
The websocket script is still added no matter the index file. The problem lies within the [gen_page](https://github.com/DioxusLabs/cli/blob/2bbf69e6b66d32ab4bed28417a95aa9f23360c6d/src/builder.rs#L422) function.

**Steps To Reproduce**

- Create a new Dioxus app and add any rsx.
- Create an index.html file in the project root with the following HTML:
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <div id="main"> </div>
</body>

</html>
```
- Run ``dioxus serve``

**Expected behavior**

All necessary scripts are added when using a custom index file.

**Environment:**
 - Dioxus version: Master
 - Rust version: Stable
 - OS info: Windows 10
 - App platform: Web

**Questionnaire**
- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix, and I have a solution
- [x] I don't have time to fix this right now, but maybe later

**Comment by mrxiaozhuox** [comment]
I think you need use cli to create index.html file, `dioxus config custom-html`

**Comment by DogeDark** [comment]
If it could add the script on its own or at least display a warning that the ``dioxus config custom-html`` command needs to be used, that'd be great. Somebody like me will eventually experience the same issue without any identification as to why.
