### ISSUE TITLE
Release build omits call to wasm start

### ISSUE THREAD

**Issue by naturalethic** [DioxusLabs/cli#27]
When building in release mode, the line at the bottom of the build `.js` file starting the wasm module is missing.

Debug mode:
```js
wasm = instance.exports;
init.__wbindgen_wasm_module = module;
wasm.__wbindgen_start();
return wasm;
```

Release mode:
```js
wasm = instance.exports;
init.__wbindgen_wasm_module = module;

return wasm;
```

**Comment by mrxiaozhuox** [comment]
We just use `wasm-bindgen` crate to generate `.js` file.

**Comment by naturalethic** [comment]
Yeah I didn't see anything specific in dioxus cli that would influence this, however I'm not sure where to look next.  Is this only happening for me?  Maybe need crate upgrade?

**Comment by naturalethic** [comment]
Testing with Trunk - has the same issue.  Very strange.

**Comment by mrxiaozhuox** [comment]
> Testing with Trunk - has the same issue. Very strange.

because `dioxus-cli` earliest code come from `trunk`
