### ISSUE TITLE
SASS support like trunk would be awesome

### ISSUE THREAD

**Issue by maccesch** [DioxusLabs/cli#33]

**Comment by mrxiaozhuox** [comment]
This feature will be implemented later.

**Comment by mrxiaozhuox** [comment]
What is the common file suffix for sass ?

**Comment by mrxiaozhuox** [comment]
> There are actually two dialects of SASS and they have their own suffix: `.sass` and `.scss`

Do we need to support all this ?

**Comment by maccesch** [comment]
I'm afraid  so. But it’s the same compiler so it shouldn’t be difficult.
