### ISSUE TITLE
Do you have any plans to add cache control?

### ISSUE THREAD

**Issue by makoven** [DioxusLabs/cli#50]
Bundlers often add a hash to the end of generated files to get around the problem of aggressive browser caching.

For example, `style.scss` becomes `style-123thisfilehash.css`

Are you planning to add something like this?

**Comment by mrxiaozhuox** [comment]
Will the SASS converter auto-generate this file?

**Comment by makoven** [comment]
@mrxiaozhuox sure. Sass is built into the dioxus-cli toolkit

**Comment by inf0rm4tik3r** [comment]
+1
Kind of important if you want to use any cache-busting (Service-Workers!).
If not supported by the build-tool itself, everyone would need to add hashes manually in their build-pipelines.
The way trunk does it currently, adding at least a hash to the final wasm and css file, works for me.
Ideally, every bundled asset should be able to receive the hash I think.

**Comment by mrxiaozhuox** [comment]
We have a plug-in system now, so I think we will start a sass support plugin, and I will close this issue.
