### ISSUE TITLE
dioxus-cli installation  failed

### ISSUE THREAD

**Issue by allenli178** [DioxusLabs/cli#59]
When I use `cargo install dioxus-cli` to install dioxus-cli, I met this bug.
The version of dioxus-cli is 0.1.4.
![image](https://user-images.githubusercontent.com/53218750/185102410-ee3171bd-3d5f-4e80-917d-796b98d83884.png)
I think someone commented out the code `notify::Config::default()`.

**Comment by trevyn** [comment]
Try `cargo install --git https://github.com/DioxusLabs/cli`

Maybe a new release is in order?

**Comment by dxps** [comment]
To me, it looks the same as my yesterday case, presented [here](https://github.com/DioxusLabs/cli/issues/4#issuecomment-1214829647).

**Comment by mrxiaozhuox** [comment]
you can just install from git repo now.

**Comment by dxps** [comment]
I can confirm the installation from git works, as previously advised.
Just did it in my other system.

**Comment by dxps** [comment]
Now trying it, I noticed a small issue with it. Shall I raise a different issue related to it :grey_question: 

```shell
$ dioxus create router_test
[INFO] 🔧 Start to create a new project 'router_test'.
[WARN] Tool is not installed: cargo-generate, try to install it.
    Updating crates.io index
  Downloaded cargo-generate v0.16.0
   ...
   Compiling cargo-generate v0.16.0
    Finished release [optimized] target(s) in 2m 35s
  Installing /home/dxps/.cargo/bin/cargo-generate
   Installed package `cargo-generate v0.16.0` (executable `cargo-generate`)
[1/9]   Done: .gitignore
[2/9]   Done: Cargo.toml
[3/9]   Done: Dioxus.toml
[4/9]   Done: LICENSE
[5/9]   Done: README.md
[6/9]   Done: public/.gitkeep
[7/9]   Done: public
[8/9]   Done: src/main.rs
[9/9]   Done: src
$ 
```
and a `router-test` (instead of `router_test`) is created.

**Comment by mrxiaozhuox** [comment]
@dxps  yeah, maybe you need create a new issue. 😄
