### ISSUE TITLE
Turning project name from snake_case into kebab-case

### ISSUE THREAD

**Issue by dxps** [DioxusLabs/cli#60]
Hi Dioxus nice people! :blush: 

Using Dioxus CLI v.`0.1.5`, there are a couple of small issues with the creation part:
1. Snake case names (like `some_project`) become kebab case names (like `some-project`).
2. Probably as a side effect, the project name in `Cargo.toml` also gets specified using kebab case.

```
$ dioxus create router_test
[INFO] 🔧 Start to create a new project 'router_test'.
[WARN] Tool is not installed: cargo-generate, try to install it.
    Updating crates.io index
  Downloaded cargo-generate v0.16.0
   ...
   Compiling cargo-generate v0.16.0
    Finished release [optimized] target(s) in 2m 35s
  Installing /home/dxps/.cargo/bin/cargo-generate
   Installed package `cargo-generate v0.16.0` (executable `cargo-generate`)
[1/9]   Done: .gitignore
[2/9]   Done: Cargo.toml
[3/9]   Done: Dioxus.toml
[4/9]   Done: LICENSE
[5/9]   Done: README.md
[6/9]   Done: public/.gitkeep
[7/9]   Done: public
[8/9]   Done: src/main.rs
[9/9]   Done: src
$ 
```
Ofc, once `cargo-generate` is already installed, things look kinda similar:
```shell
❯ dioxus create some_project
[INFO] 🔧 Start to create a new project 'some_project'.
[1/9]   Done: .gitignore
[2/9]   Done: Cargo.toml
[3/9]   Done: Dioxus.toml
[4/9]   Done: LICENSE
[5/9]   Done: README.md
[7/9]   Done: public
[8/9]   Done: src/main.rs
[9/9]   Done: src
[ERROR] 🚫 Create project failed: I/O Error: No such file or directory (os error 2)
❯
```
As before, a `some-project` folder is created.

**Comment by mrxiaozhuox** [comment]
I think this problem has been fixed in some PR.

**Comment by dxps** [comment]
I just tried with ver. 0.2.0 that at this time of this writing comes installed with cargo (using `cargo install --git https://github.com/DioxusLabs/cli`).
The outcome is actually worse.

```shell
/tmp ❯ dioxus --version
dioxus 0.2.0
/tmp ❯ 
/tmp ❯ dioxus create project_name
Error: CargoError("Failed to find the cargo directory")
/tmp ❯
```

**Comment by dxps** [comment]
@mrxiaozhuox  Could you please review the PR?
I looked into this, found two small problems and solved this issue. 
Happy to contribute, not just complain. :yum:

**Comment by mrxiaozhuox** [comment]
OK, Thank you very much 😄
