### ISSUE TITLE
Without the build (`dist` folder), `dioxus serve` fails

### ISSUE THREAD

**Issue by dxps** [DioxusLabs/cli#61]
Hi everyone!

Without the `dist` folder, `dioxus serve` fails with `I/O Error: No such file or directory (os error 2)`.
Using dioxus CLI ver. `0.1.5`.

```shell
❯ dioxus serve
[ERROR] 🚫 Serve startup failed: I/O Error: No such file or directory (os error 2)
❯ 
```

This happens right after creating a new project (as the build is not done automatically) or if you remove it (or use `dioxus clean`).

A simple message such as _"You need to build it before starting it."_ would improve the user (dev) experience.

**Comment by mrxiaozhuox** [comment]
Thank for you report,

I think we need create dir before serve start.

**Comment by dxps** [comment]
Sure, glad to help and contribute!

By _"create dir"_ you mean to build it first, I assume.
Otherwise, just creating (as in `mkdir`) the `dist` is not enough.

**Comment by mrxiaozhuox** [comment]
> Sure, glad to help and contribute!
> 
> By _"create dir"_ you mean to build it first, I assume. Otherwise, just creating (as in `mkdir`) the `dist` is not enough.

I don't know why we have this problem, some older version don't have the same problem.

**Comment by dxps** [comment]
Let's see if we can figure this out ... 
Definitely, people would have to use this version or newer ones, due to that compilation error related to `notify`.
