### ISSUE TITLE
dioxus build - Failed to parse `name` custom section

### ISSUE THREAD

**Issue by dxps** [DioxusLabs/cli#62]
Hi everyone!

Using dioxus CLI ver. `0.1.5`, when building the project a warning message is thrown.
However, the details are not descriptive enough to be addressed by the user.

```shell
❯ dioxus build
[INFO] 🚅 Running build command...
[INFO] 👑 Build done.
[WARN] failed to parse `name` custom section Invalid name type (at offset 17635851)
❯ 
```

**Comment by mrxiaozhuox** [comment]
We don't know how to fix this problem, but this warn info does not affect the project.

**Comment by dxps** [comment]
That is correct. Ok, I'll try to find some time this weekend, see if I can get a clue about it. :blush:

**Comment by dxps** [comment]
It looks like that this warning is being thrown by the [`wasmparser`](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasmparser), an indirect dependency.

For versions 0.59.0 or 0.77.0 (as per cargo tree) there is this code:
```rust
    pub(crate) fn read_name_type(&mut self) -> Result<NameType> {
        let code = self.read_var_u7()?;
        match code {
            0 => Ok(NameType::Module),
            1 => Ok(NameType::Function),
            2 => Ok(NameType::Local),
            _ => Err(BinaryReaderError::new(
                "Invalid name type",
                self.original_position() - 1,
            )),
        }
    }
```

Meanwhile, this part evolved (as [shown here](https://github.com/bytecodealliance/wasm-tools/blob/main/crates/wasmparser/src/binary_reader.rs#L2131)), and it knows about more [`NameType`](https://github.com/bytecodealliance/wasm-tools/blob/e7d3b547279fc1ab50c38db80cfa7a7a65caa16d/crates/wasmparser/src/readers/core/names.rs#L30) values.

**Comment by mrxiaozhuox** [comment]
So we can only wait.
