### ISSUE TITLE
Cannot install cli from git

### ISSUE THREAD

**Issue by RobertoSnap** [DioxusLabs/cli#79]
After successfull install from git(9c5b2cc2ea49210df47f7130fe9829155a295cc8) then when running serve in template repo I get this message:

```bash
[ERROR] 🚫 Serve startup failed: error[E0583]: file not found for module `sys`
   --> /Users/robin/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/lib.rs:124:1
    |
124 | mod sys;
    | ^^^^^^^^
    |
    = help: to create the module `sys`, create file "/Users/robin/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/sys.rs" or "/Users/robin/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/sys/mod.rs"
```

It refers to this line
<img width="450" alt="CleanShot 2022-11-15 at 08 45 29@2x" src="https://user-images.githubusercontent.com/4772930/201859516-7498f80c-1cf7-40f2-9809-17049d9509dd.png">

Im on MacM1

**Comment by mrxiaozhuox** [comment]
`dioxus serve` target is a wasm package, so your code can't include any about system & std code.

**Comment by mrxiaozhuox** [comment]
or you can use `--platform desktop` to change the target.
